# Generated by Django 3.1 on 2020-09-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
